### ISSUE TITLE
addHeader 好像没啥效果。

### ISSUE THREAD

**Issue by jxpanda** [ejlchina/okhttps#16]

**Comment by ejlchina** [comment]
代码截图

**Comment by jxpanda** [comment]
![image](https://user-images.githubusercontent.com/7555777/95836854-82fd4000-0d72-11eb-8f86-eb7cbe9bf269.png)

**Comment by ejlchina** [comment]
这个图片，我这边加载不出来看不到，你加我微信，1573555987(备注 okhttps)，我把你拉到群里交流吧

**Comment by ejlchina** [comment]
F。:
在Application中初始化了，okhttp，

F。:
[图片]

乔伊:
App.getHttp() 这个方法怎么写的？

F。:
[图片]

乔伊:
截图全一点

F。:
屏幕就这么点大

乔伊:
一共添加了几个拦截器？

F。:
[图片]

F。:
全在这

乔伊:
那应该是可以的，你让后端把请求头遍历一下，应该能拿到的

F。:
我这边， 用其他网络请求，添加头， 是没问题的 。

乔伊:
你用哪个 jar 包

乔伊:
okhttps-gson 吗？

F。:
fastjson

乔伊:
[图片]

乔伊:
这个 返回什么？

疯狂的蜗牛:
不要用fastjson 坑太多了

F。:
Map<String,String>

F。:
那我换gson试试

乔伊:
应该和 fastjson 没太大关系的

F。:
好吧

F。:
实在不行，我就换别的了。

乔伊:
后端是收不到这个请求，还是收到了请求，就是请求头 拿不到？

F。:
请求头有问题 。

F。:
拿不到content—type

乔伊:
还有这地方你在构建 HTTP 的时候没有添加 MsgConvertor

F。:
好像没有添加。但是这步不影响吧。

乔伊:
[图片]

F。:
OK

乔伊:
没有添加 Map<String,String> 就转换不成 json

F。:
那如果我在拦截器那里添加头呢？

乔伊:
okhttps-fastjson 里有 FastjsonMsgConvertor ，你可以添加这个

F。:
行

F。:
在拦截器那里添加头的话， 是不是就不需要添加这个了。

乔伊:
添加这个后，它其实会自动添加 Content-Type 头，不需要再拦截器里再加了

F。:
我是把这边删掉了 ，就在拦截器那里添加了。

乔伊:
在拦截器里添加了，最终会以拦截器里添加的头 为准，但是如果不添加 FastjsonMsgConvertor，请求的报文体就不是 json 格式了

F。:
了解了， 我去试试。

F。:
谢谢大佬～ 就是这个原因。
