### ISSUE TITLE
为什么用的还是okhttp3，而不用okhttp4呢？

### ISSUE THREAD

**Issue by mostcool** [ejlchina/okhttps#22]
看到依赖的还是okhttp3，版本3.14.9。
为什么不用okhttp4呢？

**Comment by ejlchina** [comment]
默认依赖的是 3.14.9，但是已经全面兼容 4.x 的版本
默认依赖不是 4.x 是因为 4.x 是 kotlin 重写的版本
一是 包体积相对较大，
二是 对于 没有 kotlin 依赖的的纯 java 项目使用会有问题。

所以综合考虑，默认依赖还是 3.x 的最新版本，如果你是 kotlin 项目，可以覆盖依赖使用 4.x 的版本
