### ISSUE TITLE
Crash when throw JsonSyntaxException and doesn't callback through exceptionListener or setOnException. 

### ISSUE THREAD

**Issue by dpmaycry** [ejlchina/okhttps#24]
**Describe the bug**
服务器正常应返回json，但是异常情况下返回html，exceptionListener  和 setOnException不会走直接崩溃
```
    com.ejlchina.okhttps.internal.HttpException: 转换失败
     Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
     Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

```

**To Reproduce**
这样用的

```java
http = HTTP.builder()
                .addMsgConvertor(new GsonMsgConvertor())
                .baseUrl(Constant.getApiBaseUrl())
                .exceptionListener((HttpTask<?> task, IOException error) -> {
                  error.printStackTrace();
                  return true;
                })
                .build();

try{
            http.async(Constant.LOGIN_SUFFIX)
                    .bodyType("json")
                    .setBodyPara(user)
                    .setOnResBean(new TypeRef<BaseResp<LoginResp>>() {}, result -> {
                        callback.onResponse(result);
                    })
                    .setOnException(ex ->{
                        callback.onFail(ex);
                    })
                    .post();
        }catch (Exception e){
            e.printStackTrace();
        }
```

**Expected behavior**
期望 json转换异常也会在onexception抛出.

**Smartphone (please complete the following information):**
 - Device: HongMi2s
 - OS: Android 7.1.2
 - Version OKHTTPS 3.0.0-Gson

**Comment by dpmaycry** [comment]
我的 忘记setOnException了

**Comment by ejlchina** [comment]
请参考 https://okhttps.ejlchina.com/v3/foundation.html#%E5%BC%82%E6%AD%A5%E8%AF%B7%E6%B1%82%E7%9A%84%E5%BC%82%E5%B8%B8
https://okhttps.ejlchina.com/v3/configuration.html#%E5%85%A8%E5%B1%80%E5%9B%9E%E8%B0%83%E7%9B%91%E5%90%AC
![image](https://user-images.githubusercontent.com/29403889/108580491-a78fa700-7366-11eb-9c56-bc8098ab2c06.png)

**Comment by ejlchina** [comment]
Json 转换相关异常 属于用于的 开发者可控的 编码错误，必须要修改代码才可以
这种异常不属于 开发者不可控的 网络异常，所以不提供异常回调

如果这种 编码错误也 提供了异常回调，让它不再抛出，那么开发者就很可能发现不了这个错误，从而导致错误流到产生环境，导致更严重的问题。

**Comment by dpmaycry** [comment]
如果没有json转换器，由开发者自行json转换，这么做合理，也可控。但是在使用json转换器的情况下，一旦出现后台返回异常，客户端的可靠性就无法保证，尤其是Android app中表现为直接闪退。
实际生产环境发现问题，修改周期会比较长，这段时间造成的用户影响就很大了。

**Comment by ejlchina** [comment]
可以再全局回调监听里 提前 处理 后台返回异常 的情况，全局回调兼容 具有 “阻断” 机制，当后台返回的数据 不正常时，可以 阻断 OnResponse 系列回调的执行，就可以了

**Comment by dpmaycry** [comment]
> 可以在全局回调监听里 提前处理 后台返回数据异常 的情况，全局回调 具有 “阻断” 机制，当后台返回的数据 不正常时，可以 阻断 OnResponse 系列回调的执行，就可以了

好的 谢谢~
