### ISSUE TITLE
经常会报The destination [" + destination + "] has already been subscribed!这个异常

### ISSUE THREAD

**Issue by yk007** [ejlchina/okhttps#28]
每次都是在Stomp连接成功的回调里面开始订阅，订阅之前会执行一次取消订阅方法，但是有时候过了很久APP会奔溃报上述异常；
还有登录成功或者打开首页都会执行Stomp的连接方法导致同时可能发起多个连接请求；只通过stomp.isConnected()判断也不可靠，因为有时候真在连接中
 //设置监听
        stomp.setOnConnected(new OnCallback<Stomp>() {
            @Override
            public void on(Stomp data) {
                // 服务器连接成功回调
                Log.i("Stomp", "OnConnected");
                //开始订阅消息
                subscribe();
            }
        });

           //取消订阅
            stomp.unsubscribe(destination);
            //订阅
            stomp.subscribe(destination,null,(com.ejlchina.stomp.Message msg) -> {

          }

**Comment by ejlchina** [comment]
这个异常是 重复订阅 同一个目的地造成，检查一下代码是否有这种逻辑存在呢

**Comment by ejlchina** [comment]
下个版本：同一个 Stomp 实例在重连后 将会自动 subscribe 未被 unsubscribe 的 destination

**Comment by yk007** [comment]
因为各种原因可能会出现连接断开的问题，比如网络断开等，当网络恢复后我会重新调用一次连接方法，当重新连接成功后就收不到之前的订阅发送的消息了，就必须重新订阅一下，而重新订阅之前我会调用unsubscribe 方法保证不会重复订阅，因为没有找到判断目的地 是否订阅的api就只能这样操作

**Comment by yk007** [comment]
请问大神有没有完整的Demo, 没有在源码中找到

**Comment by ejlchina** [comment]
如果你保证了所有 destination 都是 unsubscribe 过后再 subscribe，那应该不会有问题呀
