### ISSUE TITLE
Stomp 使用的是自签的https 需要配置sslSocketFactory和hostnameVerifier

### ISSUE THREAD

**Issue by yk007** [ejlchina/okhttps#29]
WebSocketTask webSocketTask = OkHttps.webSocket(UrlConfig.WS_STOMP);
stomp = Stomp.over(webSocketTask);
这么没有api可以获取到OkHttps中的http来设置sslSocketFactory

  public static WebSocketTask webSocket(String url) {
        return getHttp().webSocket(url);
    }

static synchronized HTTP getHttp() {
        if (http != null) {
            return http;
        }
        HTTP.Builder builder = HTTP.builder();
        ConvertProvider.inject(builder);
        Config.config(builder);
        http = builder.build();
        return http;
    }
我需要Https中的http对象
 http .config(b -> {
        b.sslSocketFactory(mySSLSocketFactory, myTrustManager);
        b.hostnameVerifier(myHostnameVerifier);
    })

**Comment by ejlchina** [comment]
类 `OkHttps` 是一个工具类，关于它的配置可参考文档：https://okhttps.ejlchina.com/v3/getstart.html#%E9%85%8D%E7%BD%AEokhttps

**Comment by yk007** [comment]
非常感谢，用了 SPI 方式注入自定义配置完美解决问题

**Comment by yk007** [comment]
现在又发现了一个新问题，大概一分钟Stomp就会自动断开连接，后发打印日志发现是我这边发送的断开连接请求，心跳也去掉了，还是会自动断开

**Comment by yk007** [comment]
由于服务器那边没有心跳，我这边也把心跳去掉了，会不会是这个引起的？

**Comment by ejlchina** [comment]
Stomp 自动断开连接，应该是心跳原因

**Comment by yk007** [comment]
webSocketTask.heatbeat(0, 0);
pingSeconds 客户端心跳间隔秒数（0 表示不需要心跳）
pongSeconds 服务器心跳间隔秒数（0 表示不需要心跳）
这样把心跳去掉后大概还是一分钟就自动断开，这个一分钟是哪里设置的
2021-05-24 13:56:57.414  I/Stomp: wsurl=https://*******/api/ws/websocket
2021-05-24 13:57:36.549  I/Stomp: OnConnected
2021-05-24 13:57:36.550  I/Stomp: /user/1396050115241521153/message
2021-05-24 13:58:36.868  I/Stomp: OnDisconnected
2021-05-24 13:58:36.868  I/Stomp: 连接断开自动取消订阅

**Comment by yk007** [comment]
经过排查代码应该是没有问题的，本地测试服务器不会断开，只有生产环境会，并且服务器是在海外的，这方面的原因还需要进一步排查

**Comment by ejlchina** [comment]
那可能是服务器端检测没有心跳断开了，或者中间的 路由器或网关 检测到该链接空闲太久 把它关了
