### ISSUE TITLE
Stomp有办法销毁websocket吗

### ISSUE THREAD

**Issue by chengxinping** [ejlchina/okhttps#30]
在activity界面初始化连接stomp  activity destory调用的disconnect之后回到首页 断网之后还能收到setOnException里面的回调 disconnect没有销毁websocket吗

**Comment by chengxinping** [comment]
![Uploading image.png…]()

**Comment by ejlchina** [comment]
方法 `disconnect()` 会先发送一个 `DISCONNECT` 消息给服务器，等到服务器的回复后，才会断开 websocket 连接，这么做是为了保证在连接 真正断开前，双方已经发出的数据尽量都被对方接收到。

如果确实要 **立即** 断开连接，可以这么做：
```java
WebSocketTask wesocket = OkHttps.webSocket("wss://...").heatbeat(20, 20)
Stomp stomp = Stomp.over(wesocket);

// 立即断开连接
wesocket.close();
```

**Comment by ejlchina** [comment]
v3.1.0 将新增一个 `disconnect(boolean immediate)` 方法，用于立即断开连接

**Comment by ejlchina** [comment]
v3.1.0 已发布
