### ISSUE TITLE
使用Stomp出现粘包问题

### ISSUE THREAD

**Issue by zhouzl18** [ejlchina/okhttps#31]
stomp.topic("/your-topic", (Message msg)
订阅收到数据后，我的Message是多条消息，请问这个该如何解析？

**Comment by ejlchina** [comment]
收到多条消息，应该执行多次回调，不是这样吗？

**Comment by zhouzl18** [comment]
不是的，是出现了粘包的情况，本来应该是多次回调，但是多条消息被粘在了一起，导致数据解析的时候每次只能获取第一条。收到的数据格式是这样的：
Receive STOMP message: MESSAGE
    xxx:y1
    subscription:44a0a158-d0f3-4b26-ab6e-5278945db83e
    
    {"name":"123"}��MESSAGE
    xxx:y2
    subscription:44a0a158-d0f3-4b26-ab6e-5278945db83e
    
    {"name":"22"}��MESSAGE
    xxx:y1=3
    subscription:44a0a158-d0f3-4b26-ab6e-5278945db83e
    
    {"name":"33"}��MESSAGE
    xxx:y4
    subscription:44a0a158-d0f3-4b26-ab6e-5278945db83e
    
    {"name":"44"}��
    
    这种情况该如何获取数据，多条消息粘在一起了。我看代码只解析了第一条。

**Comment by ejlchina** [comment]
明白了，v3.1.0 中修复这个问题

**Comment by ejlchina** [comment]
v3.1.0 已发布
