### ISSUE TITLE
oppo reno5手机锁屏一段时间再点亮  websocket断连 走到OnException 报错Software caused connection abort

### ISSUE THREAD

**Issue by chengxinping** [ejlchina/okhttps#36]
```
.setOnException {
                if (!this.isDestroyed) {
                    Log.e("cxp", "error:${it.message}")
                 

                  mStomp.connect()
                }
            }
```
并且在异常中重新connect 无效

**Comment by ejlchina** [comment]
1、软件使用的是哪个版本？
2、`setOnException` 方法指的是类 `WebSocketTask` 还是 `Stomp` 中的方法?
3、这个异常只在 oppo reno5 上才能复现吗？
4、可以提供一个可复现此问题的最小代码仓库地址吗？

**Comment by chengxinping** [comment]
1. 版本是3.1.1
2.异常方法是3.1.1新增的Stomp里面的方法
3.在华为  复现情况有点复杂 不能查usb充电才能复现 我怀疑是手机系统省电策略导致的  未充电情况下锁屏一段时间后网络断开导致连接失败 我在异常回调里面再次调用`onConnect`方法 日志有pong心跳 但是收不到订阅 并且没有走到`setOnConnected`回调

**Comment by chengxinping** [comment]
`       mStomp = Stomp.over(
            OkHttps.webSocket(
                "${CommonConstants.WEB_SOCKET_URL}?user_id=${kv.decode<String>(Constants.KV_LOGIN_AID)}&token=${
                    kv.decode<String>(
                        Constants.KV_LOGIN_TOKEN
                    )
                }"
            )
            .setOnException {
                if (!this.isDestroyed) {
                    Log.e("cxp", "stomp error:${it.message}")
                    isReconnect = true
                    MainScope().launch {
                        tv_notify_status.text = "未连接"
                        iv_status.imageResource = R.drawable.bg_point_red_corners_9
                        view_can_not_use.visibility = View.VISIBLE
                    }
                    mStomp.connect()

                }
            }`

**Comment by chengxinping** [comment]
```kottlin
  mStomp = Stomp.over(
            OkHttps.webSocket(
                "${CommonConstants.WEB_SOCKET_URL}?user_id=${kv.decode<String>(Constants.KV_LOGIN_AID)}&token=${
                    kv.decode<String>(
                        Constants.KV_LOGIN_TOKEN
                    )
                }"
            )
                .heatbeat(20, 20)
        )
            .setOnException {
                if (!this.isDestroyed) {
                    Log.e("cxp", "stomp error:${it.message}")
                    isReconnect = true
                    MainScope().launch {
                        tv_notify_status.text = "未连接"
                        iv_status.imageResource = R.drawable.bg_point_red_corners_9
                        view_can_not_use.visibility = View.VISIBLE
                    }
                    mStomp.connect()

                }
            }
          .setOnConnected { stomp ->
              //连接回调
}
```

**Comment by chengxinping** [comment]
![image](https://user-images.githubusercontent.com/18040985/122698124-44147800-d279-11eb-8889-6f7f6f82fc9d.png)
这是异常断开之后重新连接的日志  但是收不到订阅返回的消息

**Comment by chengxinping** [comment]
也没有走到`setOnConnected `回调

**Comment by ejlchina** [comment]
执行了 `OnException` 回调后，有没有继续走 `OnDisconnected` ？

**Comment by chengxinping** [comment]
> 执行了 `OnException` 回调后，有没有继续走 `OnDisconnected` 回调？

有走onDisConnected回调

**Comment by ejlchina** [comment]
OK，明白了，这个一个 BUG。
当前避免这个问题的方法：在 APP 中监听手机锁屏事件，在锁屏后，主动断开连接，解锁后再进行重连。

这个 BUG 将在 v3.1.2 中修复。

**Comment by ejlchina** [comment]
修复后的效果是：在 `OnException` 回调中重新调用 `connect` 将有效，并且连接后会自动订阅之前的主题与队列。

**Comment by chengxinping** [comment]
之前在老版本（2.5.1）在websockt的OnException里面实现的重连（断开网络再连上网络）没问题  升级3.1.1版本之后失效也是因为同一个原因吗

**Comment by ejlchina** [comment]
是的

**Comment by ejlchina** [comment]
我看错了，既然有 走 `OnDisconnected` 回调那就是对的，你在 `OnDisconnected` 回调里去 重连 `connect` 就好了

**Comment by chengxinping** [comment]
> 我看错了，既然有 走 `OnDisconnected` 回调那就是对的，你在 `OnDisconnected` 回调里去 重连 `connect` 就好了

**Comment by ejlchina** [comment]
严格来讲，只有在断开（`OnDisconnected`）之后，才能再次连接（`connect `）  不过 v3.1.2 后，`OnException` 回调里也会支持 调用 `connect` 方法

**Comment by chengxinping** [comment]
在onDisconnect里面重连是不行的  比如断网情况下不断重连 重连几次后就停止了 是不是无网没连上就没走onDisconnect

**Comment by ejlchina** [comment]
那就判断一下是否连连接成功过（OnOpen），如果有连成功过，则在 onDisconnect 里面重连，如果还没有连成功就 OnException 了，则在 OnException 里直接重连

**Comment by ejlchina** [comment]
连接成功后然后在异常的情况下，在 `OnException` 里面使用 `connect ` 后还是会有问题，以后版本还会和 v3.1.1 保持一致。
只有在尚未连接成功的情况下才允许在  `OnException` 里面重连。

v3.2.0 会考虑自动重连功能。
