### ISSUE TITLE
Stomp 有方法判断是否订阅过某个主题吗

### ISSUE THREAD

**Issue by chengxinping** [ejlchina/okhttps#37]
目前我的操作是在连接成功的回调里面订阅某个主题  新版本断开重连后又会走到连接成功的回调导致报错不能重复订阅

**Comment by ejlchina** [comment]
重新连接后，之前订阅的目的地 都会自动订阅一遍，不需要再重复订阅

**Comment by chengxinping** [comment]
问题是应该在哪订阅主题啊  难道不应该在成功的回调里面订阅吗  在其他位置订阅不合理啊  
在成功回调里面订阅 断开重连又会报重新订阅的错。。。

**Comment by ejlchina** [comment]
可以再连接之前 预先订阅，不必要一定在成功回调里订阅
