### ISSUE TITLE
OkHttps.sync

### ISSUE THREAD

**Issue by yuxicun** [ejlchina/okhttps#38]
请问下 OkHttps.sync 该用法怎么配置proxy 代理地址和端口?

**Comment by ejlchina** [comment]
请看文档：

https://okhttps.ejlchina.com/v3/getstart.html#%E9%85%8D%E7%BD%AEokhttps
https://okhttps.ejlchina.com/v3/questions.html#%E6%94%AF%E6%8C%81%E4%BB%A3%E7%90%86-proxy-%E5%90%97
