### ISSUE TITLE
TypeRef的T如何动态指定Class呢？

### ISSUE THREAD

**Issue by mostcool** [ejlchina/okhttps#40]
请问，TypeRef的T如何动态指定Class呢？
就是包装了一个方法，传入一个Class类型，然后TypeRef根据这个类型来反序列化json

**Comment by ejlchina** [comment]
例如：
```java
Result<User> result = OkHttps.sync("/user/1").get().getBody().toBean(new TypeRef<Result<User>>(){});
```

**Comment by mostcool** [comment]
> 例如：
> 
> ```java
> Result<User> result = OkHttps.sync("/user/1").get().getBody().toBean(new TypeRef<Result<User>>(){});
> ```

这样写User是固定的，我的意思是这里怎样传去入参的Class

**Comment by ejlchina** [comment]
那就使用其它的方法，不一定要用 `TypeRef` ：
* `toBean(Class<T> type)`
* `toBean(Type type)`
* `toList(Class<T> type)`

更多可参考文档：
https://okhttps.ejlchina.com/v3/foundation.html#httpresult
