### ISSUE TITLE
websocket长时间发生异常会导致程序闪退

### ISSUE THREAD

**Issue by BaiMingxu** [ejlchina/okhttps#43]
No deadline
okio.Timeout.deadlineNanoTime(Timeout.kt:74)

**Comment by ejlchina** [comment]
添加一个全局异常监听，参考：
http://okhttps.ejlchina-app.com/v3/foundation.html#%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86
http://okhttps.ejlchina-app.com/v3/configuration.html#%E5%85%A8%E5%B1%80%E7%9B%91%E5%90%AC
