### ISSUE TITLE
com.ejlchina.okhttps.HTTP 接口是否可以直接提供无参方案

### ISSUE THREAD

**Issue by dingan-work** [ejlchina/okhttps#55]
若我设置了baseurl，后期无需其他参数的时候，总是需要在.sync(""),虽然可以将整个请求方案设为util，但我总觉得这不是一个好的办法。

**Comment by ejlchina** [comment]
只有一个请求地址吗？

**Comment by dingan-work** [comment]
@ejlchina 是的，若全都是post请求的情况下。

**Comment by ejlchina** [comment]
你这个需求比较特殊，你先参考 `OkHttps` 工具类，再写一个工具类吧，或者你写一个工具类将 `OkHttps` 工具类再封装一下。
