### ISSUE TITLE
最近在学习java桌面程序编写，目前在研究网络请求模块

### ISSUE THREAD

**Issue by llnqykfa** [ejlchina/okhttps#56]
在进行网络请求的时候报错，
com.ejlchina.okhttps.ConvertProvider: module okhttps does not declare 'uses'

**Comment by ejlchina** [comment]
1、使用的版本号？
2、还有更详细点的异常信息吗？
3、调用代码截图一下

**Comment by llnqykfa** [comment]
3.4.2
![image](https://user-images.githubusercontent.com/29851766/156965995-a7b2073f-a8ed-48ca-b2cf-a487b7f4cd3e.png)
![image](https://user-images.githubusercontent.com/29851766/156965987-6be6515c-aa9d-4343-adff-1e8b82882249.png)

**Comment by ejlchina** [comment]
用的是 JDK 哪个版本？

**Comment by llnqykfa** [comment]
openJDK 17

**Comment by ejlchina** [comment]
已在 `v3.3.2` 与 `v3.4.4` 中修复。
