### ISSUE TITLE
java.lang.NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by thegxi** [ejlchina/okhttps#65]
java.lang.NoSuchFieldError: Companion
	at okhttp3.internal.Util.<clinit>(Util.kt:70)
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
	at com.ejlchina.okhttps.okhttp.OkHttpBuilderImpl.build(OkHttpBuilderImpl.java:231)...
Environment: springboot 
Denpendencies: <dependency>
            <groupId>com.ejlchina</groupId>
            <artifactId>okhttps-fastjson</artifactId>
            <version>3.3.2</version>
        </dependency>
Example:  HTTP http = HTTP.builder()
                .baseUrl("https://api.codelife.cc")
                .build();
        http.async("/wallpaper/wallhaven")                //  http://api.example.com/users/1
                .addUrlPara("lang", "cn")
                .addUrlPara("page", 1)
                .addUrlPara("sorting", "random")
                .addUrlPara("topRange", "6M")
                .addUrlPara("q", "id:2319")
                .setOnResponse((HttpResult res) -> {
                    // 得到目标数据
                    List<WallHavenBO> result = res.getBody().toList(WallHavenBO.class);
                }).get();

**Comment by ejlchina** [comment]
请检查项目使用的 okhttp 是什么版本，应该是底层的 okhttp 版本太低了。

**Comment by thegxi** [comment]
谢谢,解决了

**Comment by miozus** [comment]
我无语了，升级适配版本指定未解决，koltlin 升级到 2.0.10 就可以了：我的组合拳

okhttp3 4.12.0
kotlin 2.0.10
okio 3.9.0

https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp/4.12.0
