### ISSUE TITLE
网络连接超时，就出现 OkHttpsException 异步请求异常

### ISSUE THREAD

**Issue by syxc** [ejlchina/okhttps#73]
com.ejlchina.okhttps.OkHttpsException: 异步请求异常

网络连接超时，就出现 OkHttpsException 异步请求异常，请问这个怎么方便在一个地方全局捕获一下，让它不至于导致 app 闪退呢？

**Comment by ejlchina** [comment]
异常处理：https://ok.zhxu.cn/v3/foundation.html#%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86

![image](https://user-images.githubusercontent.com/29403889/174939162-e734d58f-828a-4a55-8c94-b9a07a11893e.png)

**Comment by syxc** [comment]
> 异常处理：https://ok.zhxu.cn/v3/foundation.html#%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86
> 
> ![image](https://user-images.githubusercontent.com/29403889/174939162-e734d58f-828a-4a55-8c94-b9a07a11893e.png)

好的，多谢。
