### ISSUE TITLE
[Vssue]安卓 | OkHttps

### ISSUE THREAD

**Issue by ejlchina** [ejlchina/okhttps#8]
http://okhttps.ejlchina.com/v2/android.html

**Comment by Shanyaliux** [comment]
```
.callbackExecutor((Runnable run) -> {
           // 实际编码中可以吧 Handler 提出来，不需要每次执行回调都重新创建
           new Handler(Looper.getMainLooper()).post(run); // 在主线程执行
       })
```

Android  上使用这个就直接报错`android.os.NetworkOnMainThreadException`，建议这里说明一下。  

在Android 4.0以上，网络连接不能放在主线程上

**Comment by ejlchina** [comment]
你是不是在 回调里 又发起了 同步请求呀？

**Comment by Shanyaliux** [comment]
@ejlchina

> 你是不是在 回调里 又发起了 同步请求呀？

仅仅在里面添加了一个需要在主线程执行的代码

**Comment by ejlchina** [comment]
可以把你的代码贴出来看一下吗？

**Comment by Shanyaliux** [comment]
@ejlchina

> 可以把你的代码贴出来看一下吗？

```kotlin
http = HTTP.builder()
                .baseUrl(url)
                .callbackExecutor {
                    runOnUiThread(it)
                }
                .build()

        http.async("/README.md")
                .setOnResponse {
                    println(it.body.toString())

//                        Toast.makeText(this@MainActivity,"main",Toast.LENGTH_SHORT).show()

                }
                .setOnException {
                    println(it.toString())
                }
                .setOnComplete {
                    println("$it   sadads")
                }
                .get()
```

将其注释测试依旧报错

**Comment by Shanyaliux** [comment]
@Shanyaliux

> @ejlchina
> 
> > 可以把你的代码贴出来看一下吗？
> 
> ```kotlin
> http = HTTP.builder()
>                 .baseUrl(url)
>                 .callbackExecutor {
>                     runOnUiThread(it)
>                 }
>                 .build()
> 
>         http.async("/README.md")
>                 .setOnResponse {
>                     println(it.body.toString())
> 
> //                        Toast.makeText(this@MainActivity,"main",Toast.LENGTH_SHORT).show()
> 
>                 }
>                 .setOnException {
>                     println(it.toString())
>                 }
>                 .setOnComplete {
>                     println("$it   sadads")
>                 }
>                 .get()
> ```
> 
> 将其注释测试依旧报错

所有 代码直接写在MainActivity

**Comment by ejlchina** [comment]
非常感谢，问题已重现，当前可以这个方法来解决（添加一个拦截器先把 body 下载下来）：

```java
        HTTP http = HTTP.builder()
                .baseUrl("https://gitee.com/ejlchina-zhxu/okhttps")
                .config( builder -> {
                    builder.addInterceptor(chain -> {
                        Response res = chain.proceed(chain.request());
                        ResponseBody body = res.body();
                        ResponseBody newBody = null;
                        if (body != null) {
                            newBody = ResponseBody.create(body.contentType(), body.bytes());
                        }
                        return res.newBuilder().body(newBody).build();
                    });
                })
                .callbackExecutor(this::runOnUiThread)
                .build();

        http.async("/blob/master/README.md")
                .setOnResponse(res -> {
                    Log.i("HTTP", res.getBody().toString());
                })
                .get();
```

这样子就不会有问题了。

**Comment by Shanyaliux** [comment]
@ejlchina

> 非常感谢，问题已重现，当前可以用这个方法来解决（添加一个拦截器先把 body 下载下来）：
> 
> ```java
> HTTP http = HTTP.builder()
>         .baseUrl("https://gitee.com/ejlchina-zhxu/okhttps")
>         .config( builder -> {
>             builder.addInterceptor(chain -> {
>                 Response res = chain.proceed(chain.request());
>                 ResponseBody body = res.body();
>                 ResponseBody newBody = null;
>                 if (body != null) {
>                     newBody = ResponseBody.create(body.contentType(), body.bytes());
>                 }
>                 return res.newBuilder().body(newBody).build();
>             });
>         })
>         .callbackExecutor(this::runOnUiThread)
>         .build();
> 
> http.async("/blob/master/README.md")
>         .setOnResponse(res -> {
>             Log.i("HTTP", res.getBody().toString());
>         })
>         .get();
> ```
> 
> 这样子就不会有问题了。
> 
> 下个版本将解决这个问题。
> 
> 
> 
> 
> 
> 
> 
> 

您的这个OkHttps很棒，我可以引用相关内容至我的个人博客吗？我会注明出处

**Comment by ejlchina** [comment]
可以

**Comment by Shanyaliux** [comment]
@ejlchina

> 可以

非常感谢

**Comment by ejlchina** [comment]
fixed in v2.0.1
